Console.WriteLine("Hello World!");
Console.Write("Congratulations!");
Console.Write("");
Console.Write("You wrote your first line of code.");
Console.WriteLine("This is the firstline.");
Console.Write("This is the second line.");
Console.WriteLine('b');
Console.WriteLine(123);
Console.WriteLine(0.25f);
Console.WriteLine(2.625);
Console.WriteLine(12.39816m);
Console.WriteLine(true);
Console.WriteLine(false);
string firstName;
firstName = "Bob";
Console.WriteLine(firstName);
string firstName;firstName = ("Bob");
Console.WriteLine(firstName);
firstName = "Liam";
Console.WriteLine(firstName);
firstName = "Isabella";
Console.WriteLine(firstName);
firstName = "Yasmin";
Console.WriteLine(firstName);
Console.Write("Hello, Bob! You have 3 messages in your inbox.The temperature is 34.4 celcius.");